---
title: "MBA analysis"
output: html_notebook
---

```{r}
library(tidyverse)
library(arules)
library(arulesViz)
```

```{r}
glimpse(Retail)
```

```{r}
Retail$InvoiceDate <- as.Date(Retail$InvoiceDate)
```

```{r}
glimpse(Retail)
```

```{r one way to group into a list}
GroupedRetail <- Retail %>% group_by(InvoiceNo, InvoiceDate) %>%
  summarise(Descriptions = list(unique(Description)))
```

```{r the other way to group into a list. also, the better way}
GroupedRetail2 <- Retail %>% group_by(InvoiceNo,InvoiceDate) %>%
  summarise(descriptions = toString(unique(Description)))
```

```{r}
glimpse(GroupedRetail)
```

```{r}
GroupedRetail$InvoiceNo <- NULL
GroupedRetail$InvoiceDate <- NULL
```

```{r}
colnames(mba) <- c("items")
```

```{r write it out to a file in separated form}
write.csv(mba, file = "WinCoMBA.csv", quote = FALSE, row.names = TRUE)
```

```{r}
gr <- read.transactions("WincoMBA.csv", format = 'basket', sep = ',')
```

```{r}
summary(gr)
```

```{r}
association.rules <- apriori(gr, parameter = list(supp=0.001, conf=0.90, minlen=2, maxlen= 5, maxtime= 30))
```

```{r}
summary(association.rules)
```

```{r}
inspect(association.rules[1:25])
```

```{r}
write(association.rules,
      file = "association.rules.csv",
      sep = ",",
      quote = TRUE,
      row.names = FALSE)
```

```{r}
top.ruless <- head(association.rules, n=20, by = "confidence")
```

```{r}
plot(top.ruless,method="graph")
```

